services:
  mysql-db:
    env_file: .env.local
    image: mysql:8.0
    container_name: badminton_dev_db
    ports:
      - '3307:3306' 
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: 'badminton_db_dev'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  mysql-data: